name: create a comment on new issues

on:
  issues:
    types: [opened]

jobs:
  comment-with-actions:
    runs-on: ubuntu-latest
    steps:
    - name: "dump githib context"
      run: echo '${{ toJSON(github.event) }}' | jq
      shell: bash
