name: create a comment on new issues

on:
  issues:
    types: [opened]

jobs:
  comment-with-actions:
    runs-on: ubuntu-latest
    steps:
    - name: Install jq           # Added this step to install jq
      run: sudo apt-get update && sudo apt-get install -y jq
      
    steps:
    - name: "dump github context"
      run: echo '${{ toJSON(github.event) }}' | jq
      shell: bash
